version: "3.8"
services:
  react:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: react_c
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    volumes:
      - ./src:/app/src
    environment:
      - WATCHPACK_POLLING=true